src/apps/blog/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from apps.blog.api.views import PostViewSet, CategoryListCreateView

router = DefaultRouter()
router.register(r'posts', PostViewSet, basename='posts')

app_name = 'blog_api'

urlpatterns = [
    path('categories/', CategoryListCreateView.as_view(), name='categories')
] 

urlpatterns += router.urls

src/apps/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'blog'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index')
]

src/config/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.blog.urls')),
    path('api/', include('apps.blog.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.deconstruct import deconstructible

from django.utils.text import slugify
from uuid import uuid4
from os import path

from django.core.files.uploadedfile import InMemoryUploadedFile
from PIL import Image, ImageFilter
from io import BytesIO
import sys


class Category(models.Model):

    name = models.CharField(max_length=128)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Post(models.Model):

    STATUS_CHOICES = [
        ('D', 'draft'),
        ('P', 'published')
    ]

    DEFAULT_USER_PK = 1

    title = models.CharField(max_length=255)
    slug = models.SlugField()
    status = models.CharField(max_length=16, choices=STATUS_CHOICES)
    content = models.TextField()

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        default=DEFAULT_USER_PK
    )

    categories = models.ManyToManyField(
        Category,
        related_name='posts',
        blank=True
    )

    def save(self, *args, **kwargs):
        self.slug = self.slug if self.slug else slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'


@deconstructible
class UploadPostImagesPath:

    def __init__(self, postfix):
        self.postfix = postfix

    def __call__(self, instance, filename):
        user = instance.post.owner
        post = instance.post
        file = f'{str(uuid4())[:8]}-{self.postfix}{path.splitext(filename)[1]}'
        return f'user-{user.username}/posts/{post.slug}/{file}'


class PostImage(models.Model):

    SM_PATH = UploadPostImagesPath('sm')
    LG_PATH = UploadPostImagesPath('lg')
    SM_IMG_SIZE = (512, 512)

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    small = models.ImageField(upload_to=SM_PATH, blank=True, null=True)
    large = models.ImageField(upload_to=LG_PATH, blank=True, null=True)

    def save(self, *args, **kwargs):

        im = Image.open(self.large)
        output = BytesIO()

        im.thumbnail(self.SM_IMG_SIZE)
        im.save(output, format='JPEG')
        output.seek(0)

        self.small = InMemoryUploadedFile(
            output,
            'ImageField',
            'tmp.jpg',
            'image/jpeg',
            sys.getsizeof(output),
            None
        )
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Post Image'
        verbose_name_plural = 'Posts Images'

src/apps/blog/api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListCreateAPIView

from apps.blog.models import Post, PostImage, Category
from apps.blog.api.serializers import (
    PostSerializer,
    PostImageSerializer,
    CategorySerializer
)


class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def perform_create(self, serializer):
        post = serializer.save()
        for image_data in self.request.data.getlist('images'):
            image = PostImageSerializer(data={
                'post': post.pk,
                'large': image_data
            })
            image.is_valid(raise_exception=True)
            image.save()


class CategoryListCreateView(ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

src/templates/index.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Blog</title>
</head>

<body>

    <div class="container py-3 py-md-4">
        <div class="row">
            <span class="display-4">Blog api</span>
        </div>
        <div class="row mt-4">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Request</th>
                        <th scope="col">Method</th>
                        <th scope="col">Url</th>
                        <th scope="col">Data</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td
                            class="text-center"
                            colspan="4"
                        >
                            <span>Posts</span>
                        </td>
                    </tr>
                    <tr>
                        <td>Posts list</a></th>
                        <td>GET</td>
                        <td><a href="{% url 'blog_api:posts-list' %}">{{ 'posts/' }}</a></td>
                        <td>{}</td>
                    </tr>
                    <tr>
                        <td>Post create</td>
                        <td>POST</td>
                        <td><a href="{% url 'blog_api:posts-list' %}">{{ 'posts/' }}</a></td>
                        <td>{}</td>
                    </tr>
                    <tr>
                        <td>Post detail</td>
                        <td>GET</td>
                        <td><a
                                href="{% url 'blog_api:posts-detail' 1 %}">{{ 'posts/<:id>/' }}</a>
                        </td>
                        <td>{}</td>
                    </tr>
                    <tr>
                        <td>Post update</td>
                        <td>PUT</td>
                        <td><a
                                href="{% url 'blog_api:posts-detail' 1 %}">{{ 'posts/<:id>/' }}</a>
                        </td>
                        <td>{}</td>
                    </tr>
                    <tr>
                        <td>Post delete</td>
                        <td>DELETE</td>
                        <td><a
                                href="{% url 'blog_api:posts-detail' 1 %}">{{ 'posts/<:id>/' }}</a>
                        </td>
                        <td>{}</td>
                    </tr>
                    <tr>
                        <td
                            class="text-center"
                            colspan="4"
                        >
                            <span>Categories</span>
                        </td>
                    </tr>
                    <tr>
                        <td>Categories list</a></th>
                        <td>GET</td>
                        <td>
                            <a href="{% url 'blog_api:categories' %}">{{ 'categories/' }}</a>
                        </td>
                        <td>{}</td>
                    </tr>
                    <tr>
                        <td>Category create</td>
                        <td>POST</td>
                        <td>
                            <a href="{% url 'blog_api:categories' %}">{{ 'categories/' }}</a>
                        </td>
                        <td>{}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>